### ISSUE TITLE
Remove Incognito Debug

### ISSUE THREAD

**Issue by McFurSun** [Task-Force-Raider/Liberation-Livonia#12]
set to false

https://github.com/Task-Force-Raider/Missions/blob/27aa53503087cb736016440dc2cc2ca42fb575aa/kp_liberation.Enoch/INC_undercover/UCR_setup.sqf#L15

**Comment by Grewsome2018** [comment]
Ugh why doesn't my fork of the git have any of the INC folders or files lol I can't even open them up to have a peak

**Comment by Grewsome2018** [comment]
Was fixed in #13
