### ISSUE TITLE
Turn on whitelist and add Simplex Support Services (SSS) Modules/Config SSS

### ISSUE THREAD

**Issue by McFurSun** [Task-Force-Raider/Liberation-Livonia#15]
White-list the commander via the inbuilt functions to prevent shenanigans.
This will also prevent abuse of the SSS via Zeus.

Assign JTAC's and Commander as SSS requester.
Add supporrts for them to.

Add to mission a heli that can be used by anyone in lieu of HALO, via SSS.

**Comment by the-pope-himself** [comment]
UAV/INT operators have been given simplex command support. 

Commander can use Zeus if needed. Other players will need to coordinate with their UAV/INT teammates to request simplex transport.

Transport blackhawk is at main base with a five minute respawn. 

Transport helo has a "reserved" marker over it's helipad.
