### ISSUE TITLE
Ronin Loadouts (incognito players)

### ISSUE THREAD

**Issue by McFurSun** [Task-Force-Raider/Liberation-Livonia#16]
Edit loadouts to be civ based/hidden weapons.

If wanting enemy gear, they will have to "acquire" it.

**Comment by the-pope-himself** [comment]
Looked at this and realised that all gear gets stripped on spawn anyways. It can still be done but might be just as simple to create a cache of undercover gear boxes with a whitelisted ace arsenal.

**Comment by McFurSun** [comment]
Or figure out how to add mission loadouts to the ACE arsenal

**Comment by the-pope-himself** [comment]
Do we know how the compromised uniform system works? Would suck to get your cover blown, get killed, come back into the game and choose a loadouts that's already compromised.

**Comment by McFurSun** [comment]
Here's the way to add default loadouts.
https://ace3mod.com/wiki/framework/arsenal-framework.html#41-adding-default-loadouts-via-3den

As for how it works, the creator has lots of documentation.
"In MP, ensure that respawn timers are set to at least 5 seconds to give the script a chance to recognise when a unit is dead and reset values accordingly."

https://github.com/1ncontinentia/Incon-Undercover/blob/master/README.md

**Comment by the-pope-himself** [comment]
This has been completed and committed to the 1.0 branch for approval.
