### ISSUE TITLE
Victory Condition

### ISSUE THREAD

**Issue by McFurSun** [Task-Force-Raider/Liberation-Livonia#2]
Currently the victory condition is all capitals, would all sectors be better?

https://github.com/Task-Force-Raider/Missions/blob/fdb8a1cee94e97887f3aaa6ebf564e761e85a411/kp_liberation.Enoch/ui/mission_params.hpp#L123-L128

**Comment by Grewsome2018** [comment]
All sectors would require everything on the map to be done which would probably prolong it a bit more - it definitely wouldn't make things too much harder as you really need to take a lot of the sectors before you even get close to the capitals...

**Comment by McFurSun** [comment]
If we set it to All Sectors we can choose to pull the pin early anyway and still be happy that we conquered the enemy without potentially cutting ourselves short by conquering all capitals.

set line 127 to 4 ??

**Comment by the-pope-himself** [comment]
All sectors might make the ending a bit anticlimactic. Whereas with all capitals we can pick a specific date to hit the last city and have a final hurrah.

**Comment by McFurSun** [comment]
https://github.com/Task-Force-Raider/Missions/commit/6c8a7c492ac192ba2fbea4fc66d8c82baf0a2f26#diff-ce71444039669686a38a38a4127a7eb6
