### ISSUE TITLE
Ammo container can't rearm helicopters

### ISSUE THREAD

**Issue by Grewsome2018** [Task-Force-Raider/Liberation-Livonia#24]
Daffles may be able to explain it better, basically you can only rearm through the ammo truck **not** the ammo container

**Comment by BroBeansCPG** [comment]
from what i could tell it looks like it's just a range issue from the ammo container .. unfortunately this might be hardcoded into Arma/Ace

**Comment by McFurSun** [comment]
Might be worth looking at the ACE addon settings to see if we can alter it there.

Also would be good to go over all the settings as an admin team, for lib and tac nights

**Comment by BroBeansCPG** [comment]
Engine issue. Not much can be done here.
