### ISSUE TITLE
Resource Multiplier

### ISSUE THREAD

**Issue by McFurSun** [Task-Force-Raider/Liberation-Livonia#3]
Resource multiplier is x1, do we wnat x2 or x3 instead?

https://github.com/Task-Force-Raider/Missions/blob/fdb8a1cee94e97887f3aaa6ebf564e761e85a411/kp_liberation.Enoch/ui/mission_params.hpp#L111-L116

**Comment by Grewsome2018** [comment]
I think 1x is fine as I've been testing 1.25 and 1.5 lately and it has quite a big impact over time on how much you get and could potentially "cheese" progression a wee bit by letting us get a bunch of IFVs and armoured vehicles at our first FOB after just two or three village captures

**Comment by McFurSun** [comment]
Left at x1 for now.

We can always reopen the issue if it needs adjusting.
