### ISSUE TITLE
Armed SUV doesn't trigger AI if its added as a Civ vic in incon

### ISSUE THREAD

**Issue by McFurSun** [Task-Force-Raider/Liberation-Livonia#40]
Tested in Local.
They weren't interested in me when I got on the gun and pointed it at them. Only wanted me dead if I fired it.
Debug confirmed what i saw.

Removed from UCR_Setup until we can find a solution. This means they will engage on sight if you are a "civ" in the vehicle.
Vehicle is still purchasable.

**Comment by Grewsome2018** [comment]
Engine issue I'm pretty sure after looking at it

**Comment by BroBeansCPG** [comment]
No real easy way for incon to differentiate between turret states. 

Could be scripted externally though
