### ISSUE TITLE
Mobile Respawn and/or Arsenal for Ronin

### ISSUE THREAD

**Issue by McFurSun** [Task-Force-Raider/Liberation-Livonia#43]
Add to the two vehicles under the cam net at main base.

Could investigate if the arsenal crates that you buy could fit in SUV's as a temp fix.

Mobile respawn could be to OP and probably wouldn't work as it would be to close to enemy.

**Comment by the-pope-himself** [comment]
This has been done and merged into Dev Branch.

Arsenal has been added to Ronin vehicles.
No need for mobile respawn.
