### ISSUE TITLE
Reduce Sector Spawning Distance

### ISSUE THREAD

**Issue by BroBeansCPG** [Task-Force-Raider/Liberation-Livonia#49]
Look into reducing spawn distance for new sectors to reduce fps and server load

**Comment by McFurSun** [comment]
https://github.com/Task-Force-Raider/Liberation-Livonia/blob/106d982367ba85f0e4ef341431fdaefdea84e40c/kp_liberation.Enoch/kp_liberation_config.sqf#L196

what distance should we go for?

**Comment by the-pope-himself** [comment]
So that'd have to be triggered off the edge of the zone, not the middle?

Drop it down to 700 - 800 and see if there is any appreciable difference.
