### ISSUE TITLE
Update RHS/ACE/Acre arsenal preset

### ISSUE THREAD

**Issue by Grewsome2018** [Task-Force-Raider/Liberation-Livonia#6]
Check and update the arsenal preset

kp_liberation.Enoch/arsenal_presets/rhsusaf_ace_acre.sqf

**Comment by McFurSun** [comment]
Should be negated by having no restrictions  on arsenal.
Lines 207 to 212 
https://github.com/Task-Force-Raider/Missions/blob/mission-params-changes/kp_liberation.Enoch/ui/mission_params.hpp

**Comment by Grewsome2018** [comment]
Only thing with having no restrictions is that people might be able to pull out mortars and other things that you would usually have to purchase through the Build menu that you are only meant to be able to utilise in the FOBs

**Comment by BroBeansCPG** [comment]
`0  = Use the default blacklist method (defined below)`

Lines 143 - 156 
https://github.com/Task-Force-Raider/Missions/blob/mission-params-changes/kp_liberation.Enoch/kp_liberation_config.sqf

Default method includes blacklist array found on line 237. 
It's a lot easier than making a custom one. We can look into it though

**Comment by McFurSun** [comment]
It would be interesting to see if having the restricted arsenal via mission params and then use the black list method @BroBeansCPG mentions in the prev comment.

I do remember we had issues around this when trying to set it up at the beginning of the year so just reverted to setting the mission param to no restrictions.

At the end of the day we should be able to trust in TFR members not abusing the system, and if they do maybe we need to look at their retention.........

**Comment by the-pope-himself** [comment]
I don't mind the idea of some self-regulation in the arsenal. Also, if we want to do mortar training Lib is the best place to do it.

An option would be to create a set of arsenal loadouts for the guys to adhere to.

**Comment by Grewsome2018** [comment]
I'm gonna close this for the time being, in hindsight, I agree that the restrictions may be over the top and the work involved would be a bit tough. If we need to, we can just use the blacklist I guess. If it becomes an issue we can address it again later :)
